<a href="https://colab.research.google.com/github/BonnyWang/ECE160_Final/blob/master/_nnnote.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#-Intro

In [0]:
!pip install -q pyyaml  # Required to save models in YAML format

In [4]:
import tensorflow as tf
print(tf.__version__)

1.14.0


In [0]:

graph1 = tf.Graph()

In [0]:
with graph1.as_default():
  a = tf.constant([2], name = 'constant_a')
  b = tf.constant([3], name = 'constant_b')

In [7]:
a

<tf.Tensor 'constant_a:0' shape=(1,) dtype=int32>

In [8]:
sess = tf.Session(graph = graph1)
result = sess.run(a)
print(result)
sess.close()

[2]


In [0]:
with graph1.as_default():
  c = tf.add(a,b)

In [10]:
sess = tf.Session(graph = graph1)
result = sess.run(c)
print(result)
sess.close()

[5]


- to avaid close session every time
- wtih statement is used to handle exception in python
- The with statement itself ensures proper acquisition and release of resources

In [11]:
with tf.Session(graph = graph1) as sess :
  result = sess.run(c)
  print(result)

[5]


- Define Multidimenstional Array

In [12]:
graph2 = tf.Graph()
with graph2.as_default():
  Scalar = tf.constant(2)
  Vector = tf.constant([5,6,2])
  Matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
  Tensor = tf.constant( [ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]]])

with tf.Session(graph = graph2) as sess:
  result = sess.run(Scalar)
  print ("Scalar (1 entry):\n %s \n" % result)
  result = sess.run(Vector)
  print ("Vector (3 entries) :\n %s \n" % result)
  result = sess.run(Matrix)
  print ("Matrix (3x3 entries):\n %s \n" % result)
  result = sess.run(Tensor)
  print ("Tensor (3x3x3 entries) :\n %s \n" % result)

Scalar (1 entry):
 2 

Vector (3 entries) :
 [5 6 2] 

Matrix (3x3 entries):
 [[1 2 3]
 [2 3 4]
 [3 4 5]] 

Tensor (3x3x3 entries) :
 [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]] 



In [13]:
Scalar.shape

TensorShape([])

In [14]:
Tensor.shape

TensorShape([Dimension(3), Dimension(3), Dimension(3)])

- The difference between + and tf.add


In [15]:
graph3 = tf.Graph()
with graph3.as_default():
    Matrix_one = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
    Matrix_two = tf.constant([[2,2,2],[2,2,2],[2,2,2]])

    add_1_operation = tf.add(Matrix_one, Matrix_two)
    add_2_operation = Matrix_one + Matrix_two

with tf.Session(graph =graph3) as sess:
    result = sess.run(add_1_operation)
    print ("Defined using tensorflow function :")
    print(result)
    result = sess.run(add_2_operation)
    print ("Defined using normal expressions :")
    print(result)

Defined using tensorflow function :
[[3 4 5]
 [4 5 6]
 [5 6 7]]
Defined using normal expressions :
[[3 4 5]
 [4 5 6]
 [5 6 7]]


In [16]:
graph4 = tf.Graph()
with graph4.as_default():
    Matrix_one = tf.constant([[2,3],[3,4]])
    Matrix_two = tf.constant([[2,3],[3,4]])

    mul_operation = tf.matmul(Matrix_one, Matrix_two)

with tf.Session(graph = graph4) as sess:
    result = sess.run(mul_operation)
    print ("Defined using tensorflow function :")
    print(result)

Defined using tensorflow function :
[[13 18]
 [18 25]]


In [17]:
graph4 = tf.Graph()
with graph4.as_default():
    Matrix_one = tf.constant([[2,3],[3,4]])
    Matrix_two = tf.constant([[2,3],[3,4]])

    mul_operation = tf.matmul(Matrix_one, Matrix_two)

with tf.Session(graph = graph4) as sess:
    result = sess.run(mul_operation)
    print ("Defined using tensorflow function :")
    print(result)

Defined using tensorflow function :
[[13 18]
 [18 25]]


# **- Variables**

In [0]:
v = tf.Variable(0)

In [0]:

update = tf.assign(v, v+1)

In [21]:
print(update)

Tensor("Assign:0", shape=(), dtype=int32_ref)


In [0]:
init_op = tf.global_variables_initializer()

In [23]:
with tf.Session() as session:
  session.run(init_op)
  print(session.run(v))
  for _ in range(3):
    session.run(update)
    print(session.run(v))

0
1
2
3


# **-PlaceHolder**

In [0]:
 a = tf.placeholder(tf.float32)

In [0]:
b = a*2

In [26]:
with tf.Session() as sess:
  result = sess.run(b, feed_dict = {a:3.5})
  print(result)

7.0


In [27]:
dictionary={a: [ [ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ] , [ [13,14,15],[16,17,18],[19,20,21],[22,23,24] ] ] }

with tf.Session() as sess:
    result = sess.run(b,feed_dict=dictionary)
    print (result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]


In [28]:
graph5 = tf.Graph()
with graph5.as_default():
    a = tf.constant([5])
    b = tf.constant([2])
    c = tf.add(a,b)
    d = tf.subtract(a,b)

with tf.Session(graph = graph5) as sess:
    result = sess.run(c)
    print ('c =: %s' % result)
    result = sess.run(d)
    print ('d =: %s' % result)

c =: [7]
d =: [3]
